### ISSUE TITLE
Spaces instead of tabs for generated files?

### ISSUE THREAD

**Issue by achim-k** [pschillinger/flexbe_chrome_app#1]
Hi Philipp,

we would prefer if the FlexBE widget generates behavior files with spaces rather than tabs. Maybe we can add an option flag to the widget where the user can specify which white space characters are preferred.
Cheers

**Comment by pschillinger** [comment]
New option in the settings is available. The updated version is also available on master in [flexbe_behavior_engine](https://github.com/team-vigir/flexbe_behavior_engine). Make sure to update the app in Chrome/Chromium after pulling the newest version.

Note that switching to a different indentation type might require you to change indentation in the manual sections accordingly, the code generator doesn't touch them.
