### ISSUE TITLE
Negative value for a numeric Behavior Parameter default field

### ISSUE THREAD

**Issue by romainreignier** [pschillinger/flexbe_chrome_app#12]
In the dashboard view, it seems not possible to assign a default negative value to a numeric Behavior Parameter (the red circle in the attached screenshot).

![negative_behavior_parameter](https://cloud.githubusercontent.com/assets/8845664/25652015/620deb3c-2fe6-11e7-837e-e8eacedf6e3d.png)

**Comment by romainreignier** [comment]
I think that [this expression](https://github.com/pschillinger/flexbe_chrome_app/blob/master/FlexBE/src/ui/ui_dashboard.js#L716):
```js
if (this.value.match(/^[0-9]+(\.[0-9]+)?$/i) == undefined)
```
Should be replaced by [this one](https://github.com/pschillinger/flexbe_chrome_app/blob/master/FlexBE/src/ui/ui_dashboard.js#L893) which adds the '-' symbol: 
```js
if (this.value.match(/^-?[0-9]+(\.[0-9]+)?$/i) == undefined)
```

**Comment by pschillinger** [comment]
You are right, this slipped through somehow. Thank you for fixing!
