### ISSUE TITLE
[Feature] Copying of states

### ISSUE THREAD

**Issue by achim-k** [pschillinger/flexbe_chrome_app#2]
It would be great if the UI would allow copying of states :smiley:

**Comment by pschillinger** [comment]
It is not in a tutorial yet, sorry.

Ctrl + Space is the way to go. Select a set of states by dragging a reactangle across them, then press Ctrl + Space and select "Copy". All states completely inside will get copied. To paste them, just press Ctrl + Space again and select "Paste".

**Comment by achim-k** [comment]
Ah very nice. Thanks!
